#!/usr/bin/env python3
"""Generate the UEFI platform package for gauguin from Qualcomm's own config.

The two libraries a Mu-Silicium platform package has to provide are pure data:

  MemoryMapLib        the DDR and MMIO map UEFI is told about
  ConfigurationMapLib the platform tuning parameters

Both are exactly what the phone's XBL already carries in `uefiplat.cfg`, which
this project extracted into `device/config/`. So instead of hand-transcribing
~80 memory regions (and getting one wrong in a way that only shows up as a hang),
this reads Qualcomm's own numbers and emits the C.

Reference packages for the surrounding boilerplate: `MooreaPkg` (SM7150) at the
SoC level and `suryaPkg` (Xiaomi POCO X3 NFC) at the board level.

Usage:  make_uefi_platform.py [--repo DIR]
"""
import argparse
import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

sys.path.insert(0, HERE)
from make_xbl_binaries import guid_for, present_drivers   # noqa: E402  (same directory)

LICENSE = """/**
  Copyright (c) 2011-2012, ARM Limited. All rights reserved.
  SPDX-License-Identifier: BSD-2-Clause-Patent
**/
"""

GEN_NOTE = """/*
 * GENERATED by tools/make_uefi_platform.py - do not edit by hand.
 *
 * The data below is transcribed from this device's own XBL configuration
 * (device/config/uefiplat.cfg), recovered by tools/xbl_extract.py. It is
 * Qualcomm's description of this exact board, not an approximation.
 */
"""

# Values that carry over from the SoC family (SM7225/SM6350) rather than the
# board. GIC bases confirmed against both uefiplat.cfg and the device tree.
SOC_DEFAULTS = dict(
    gic_dist=0x17A00000,
    gic_redist=0x17A60000,
    cpu_model='"Snapdragon (TM) 750G @ 2.21 GHz"',
    cpu_part='"SM7225"',
    acpi_oem_table_id=0x202041544942,   # "BITRA  " little-endian
    acpi_oem_revision=0x7225,
)


def parse_uefiplat(path):
    """Return (memory_map, register_map, config_params) from uefiplat.cfg.

    The two map sections share one line format:
        0xADDR, 0xSIZE, "Label", HobOption, ResourceType, ResourceAttribute,
        MemoryType, ArmAttribute
    """
    memory, registers, params = [], [], []
    section = None
    for raw in open(path, encoding="utf-8", errors="replace"):
        line = raw.strip()
        if line.startswith("[") and line.endswith("]"):
            section = line.strip("[]")
            continue
        if not line or line.startswith("#"):
            continue
        if section in ("MemoryMap", "RegisterMap"):
            m = re.match(
                r'^(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)\s*,\s*"([^"]*)"\s*,\s*'
                r'(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*(?:,\s*(\w+))?', line)
            if not m:
                continue
            addr, size, label, hob, rtype, rattr, mtype, armattr = m.groups()
            entry = dict(addr=int(addr, 16), size=int(size, 16), label=label,
                         hob=hob, rtype=rtype, rattr=rattr, mtype=mtype,
                         armattr=armattr or "NS_DEVICE")
            (memory if section == "MemoryMap" else registers).append(entry)
        elif section == "ConfigParameters":
            m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+?)\s*$', line)
            if not m:
                continue
            key, val = m.groups()
            if val.startswith('"'):
                continue                      # strings are not map entries
            try:
                params.append((key, int(val, 0)))
            except ValueError:
                pass
    return memory, registers, params


def emit_memmap(memory, registers, out):
    w = out.write
    w(LICENSE)
    w('#include <Library/MemoryMapLib.h>\n\n')
    w(GEN_NOTE)
    w("STATIC\nEFI_MEMORY_REGION_DESCRIPTOR\ngMemoryDescriptor[] = {\n")
    w("  // Name, Address, Length, HobOption, ResourceType, ResourceAttribute, MemoryType, ArmAttribute\n")
    w("\n  // DDR Regions\n")
    for e in memory:
        w(f'  {{"{e["label"]}", 0x{e["addr"]:08X}, 0x{e["size"]:08X}, {e["hob"]}, '
          f'{e["rtype"]}, {e["rattr"]}, {e["mtype"]}, {e["armattr"]}}},\n')
    w("\n  // Register Regions\n")
    for e in registers:
        w(f'  {{"{e["label"]}", 0x{e["addr"]:08X}, 0x{e["size"]:08X}, {e["hob"]}, '
          f'{e["rtype"]}, {e["rattr"]}, {e["mtype"]}, {e["armattr"]}}},\n')
    w("};\n\n")
    w("""VOID
GetMemoryMap (
  OUT EFI_MEMORY_REGION_DESCRIPTOR **MemoryDescriptor,
  OUT UINT8                         *MemoryDescriptorCount)
{
  // Pass Data
  *MemoryDescriptor      = gMemoryDescriptor;
  *MemoryDescriptorCount = ARRAY_SIZE (gMemoryDescriptor);
}
""")
    return len(memory) + len(registers)


# Keys in [ConfigParameters] that are metadata or strings rather than platform
# parameters, and so must not appear in the UEFI configuration map. The string
# ones are already filtered out by the parser; these are the numeric ones that
# describe the file rather than the board.
CONFIG_META_KEYS = {
    "ConfigParameterCount",     # how many entries the vendor file has
}

# Values Mu-Silicium's ConfigMap expects that uefiplat.cfg does not spell out
# under a matching name. Kept explicit so their origin is visible.
CONFIG_EXTRA = [
    ("DetectRetailUserAttentionHotkey", 0x00),
    ("DetectRetailUserAttentionHotkeyCode", 0x17),
    ("EnableOEMSetupAppInRetail", 0x0),
    ("DDRInfoNotifyFlag", 0x1),
]


def emit_configmap(params, out):
    w = out.write
    w(LICENSE)
    w('#include <Library/ConfigurationMapLib.h>\n\n')
    w(GEN_NOTE)
    w("STATIC\nEFI_CONFIGURATION_ENTRY_DESCRIPTOR\ngConfigurationDescriptor[] = {\n")
    w("  // Configuration Map\n")
    n = 0
    for key, val in params:
        if key in CONFIG_META_KEYS:
            continue
        w(f'  {{"{key}", 0x{val:X}}},\n')
        n += 1
    w("  // added by the generator, not present verbatim in uefiplat.cfg\n")
    for key, val in CONFIG_EXTRA:
        w(f'  {{"{key}", 0x{val:X}}},\n')
        n += 1
    w("};\n\n")
    w("""VOID
GetConfigurationMap (
  OUT EFI_CONFIGURATION_ENTRY_DESCRIPTOR **ConfigurationDescriptor,
  OUT UINT8                               *ConfigurationDescriptorCount)
{
  // Pass Data
  *ConfigurationDescriptor      = gConfigurationDescriptor;
  *ConfigurationDescriptorCount = ARRAY_SIZE (gConfigurationDescriptor);
}
""")
    return n


BITRA_DSC_INC = """##
#  Bitra platform (Snapdragon 750G / SM7225) - generated for gauguin.
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  #
  # Timer
  #
  USE_PHYSICAL_TIMER                         = 1

  #
  # KEP
  #
  HAS_ACTLR_EL1_UNIMPLEMENTED_ERRATA         = 0
  HAS_AMCNTENSET0_EL0_UNIMPLEMENTED_ERRATA   = 0
  HAS_GIC_V3_WITHOUT_IRM_FLAG_SUPPORT_ERRATA = 0
  HAS_PSCI_MEMPROTECT_FAILING_ERRATA         = 1

!include QcomPkg/QcomPkg.dsc.inc

[BuildOptions]
  #
  # Cortex-A77 + Cortex-A55. The Kryo 570 cores implement ARMv8.2-A.
  #
  *_*_AARCH64_CC_FLAGS = -march=armv8.2-a+crypto+rcpc

[PcdsFixedAtBuild]
  #
  # ACPI
  #
  gEfiMdeModulePkgTokenSpaceGuid.PcdAcpiDefaultOemTableId|0x{acpi_oem_table_id:X}
  gEfiMdeModulePkgTokenSpaceGuid.PcdAcpiDefaultOemRevision|0x{acpi_oem_revision:X}

  #
  # CPU - 2x A77 + 6x A55
  #
  gArmPlatformTokenSpaceGuid.PcdCoreCount|8
  gArmPlatformTokenSpaceGuid.PcdClusterCount|2

  #
  # GIC. Bases agree between uefiplat.cfg and the device tree; uefiplat.cfg
  # calls the distributor GIC600, upstream calls it GIC500 - same address.
  #
  gArmTokenSpaceGuid.PcdGicDistributorBase|0x{gic_dist:X}
  gArmTokenSpaceGuid.PcdGicRedistributorsBase|0x{gic_redist:X}

  #
  # Timer
  #
  gArmTokenSpaceGuid.PcdArmArchTimerSecIntrNum|17
  gArmTokenSpaceGuid.PcdArmArchTimerIntrNum|18

  #
  # Shared RFS Area
  #
  gQcomPkgTokenSpaceGuid.PcdDestinationVmCount|2

  #
  # SMBIOS
  #
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosProcessorModel|{cpu_model}
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosProcessorPartNumber|{cpu_part}

[LibraryClasses]
  #
  # SEC Libraries
  #
  PlatformSecLib|BitraPkg/Library/PlatformSecLib/PlatformSecLib.inf

  #
  # ACPI Libraries
  #
  AcpiTableUpdateLib|BitraPkg/Library/AcpiTableUpdateLib/AcpiTableUpdateLib.inf
"""

GAUGUIN_DSC = """##
#  Xiaomi Redmi Note 9 Pro 5G (gauguin) - Snapdragon 750G / SM7225 / Bitra
#
#  GENERATED by tools/make_uefi_platform.py - values come from this device's
#  own XBL configuration and device tree.
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  PLATFORM_NAME                  = gauguin
  PLATFORM_GUID                  = 7E1B4C62-2F4A-4D18-9E31-2C5A0D8B6F41
  PLATFORM_VERSION               = 0.1
  DSC_SPECIFICATION              = 0x00010005
  OUTPUT_DIRECTORY               = Build/gauguinPkg
  SUPPORTED_ARCHITECTURES        = AARCH64
  BUILD_TARGETS                  = RELEASE|DEBUG
  SKUID_IDENTIFIER               = DEFAULT
  FLASH_DEFINITION               = gauguinPkg/gauguin.fdf
  USE_CUSTOM_DISPLAY_DRIVER      = 1

  #
  # 0 = SM7225 (Snapdragon 750G)
  #
  SOC_TYPE                       = 0

!include BitraPkg/BitraPkg.dsc.inc

[PcdsFixedAtBuild]
  #
  # DDR
  #
  gArmTokenSpaceGuid.PcdSystemMemoryBase|0x80000000

  #
  # UEFI Stack - from the "UEFI Stack" region in uefiplat.cfg
  #
  gArmPlatformTokenSpaceGuid.PcdCPUCoresStackBase|0x9FF90000
  gArmPlatformTokenSpaceGuid.PcdCPUCorePrimaryStackSize|0x40000

  #
  # SMBIOS
  #
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemManufacturer|"Xiaomi"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemModel|"Redmi Note 9 Pro 5G"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemRetailModel|"gauguin"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemRetailSku|"M2007J17C"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemBoardModel|"gauguin"

  #
  # Simple Frame Buffer - 1080x2400, the panel's native mode
  #
  gSiliciumPkgTokenSpaceGuid.PcdFrameBufferWidth|1080
  gSiliciumPkgTokenSpaceGuid.PcdFrameBufferHeight|2400
  gSiliciumPkgTokenSpaceGuid.PcdFrameBufferColorDepth|32

  #
  # Platform PEI
  #
  gQcomPkgTokenSpaceGuid.PcdPlatformType|"WP"

[LibraryClasses]
  #
  # Memory Libraries
  #
  MemoryMapLib|gauguinPkg/Library/MemoryMapLib/MemoryMapLib.inf

  #
  # QCOM Libraries
  #
  ConfigurationMapLib|gauguinPkg/Library/ConfigurationMapLib/ConfigurationMapLib.inf
"""

GAUGUIN_FDF = """##
#  Xiaomi Redmi Note 9 Pro 5G (gauguin)
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[FD.SILICIUM_UEFI]
BaseAddress   = $(FD_BASE)|gArmTokenSpaceGuid.PcdFdBaseAddress
Size          = $(FD_SIZE)|gArmTokenSpaceGuid.PcdFdSize
ErasePolarity = 1

# BlockSize * NumBlocks = Size
BlockSize     = 0x1000
NumBlocks     = $(FD_BLOCKS)

0x00000000|$(FD_SIZE)
gArmTokenSpaceGuid.PcdFvBaseAddress|gArmTokenSpaceGuid.PcdFvSize
FV = FVMAIN_COMPACT

[FV.FvMain]
FvNameGuid         = CD8D4C84-20AD-4073-8A28-3400FAE05941
BlockSize          = 0x1000
NumBlocks          = 0
FvAlignment        = 8
ERASE_POLARITY     = 1
MEMORY_MAPPED      = TRUE
STICKY_WRITE       = TRUE
LOCK_CAP           = TRUE
LOCK_STATUS        = TRUE
WRITE_DISABLED_CAP = TRUE
WRITE_ENABLED_CAP  = TRUE
WRITE_STATUS       = TRUE
WRITE_LOCK_CAP     = TRUE
WRITE_LOCK_STATUS  = TRUE
READ_DISABLED_CAP  = TRUE
READ_ENABLED_CAP   = TRUE
READ_STATUS        = TRUE
READ_LOCK_CAP      = TRUE
READ_LOCK_STATUS   = TRUE

  !include Include/APRIORI.inc
  !include Include/DXE.inc
  !include Include/RAW.inc

  # RAM Manager
  INF SiliciumPkg/Drivers/RamManagerDxe/RamManagerDxe.inf

  # SmBios
  INF MdeModulePkg/Universal/SmbiosDxe/SmbiosDxe.inf
  INF SiliciumPkg/Drivers/SmBiosTableDxe/SmBiosTableDxe.inf

  # ACPI
  INF MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableDxe.inf
  INF MdeModulePkg/Universal/Acpi/AcpiPlatformDxe/AcpiPlatformDxe.inf
  INF RuleOverride = ACPITABLE gauguin/AcpiTables.inf

  !include QcomPkg/Extra.fdf.inc

[FV.FVMAIN_COMPACT]
FvAlignment        = 8
ERASE_POLARITY     = 1
MEMORY_MAPPED      = TRUE
STICKY_WRITE       = TRUE
LOCK_CAP           = TRUE
LOCK_STATUS        = TRUE
WRITE_DISABLED_CAP = TRUE
WRITE_ENABLED_CAP  = TRUE
WRITE_STATUS       = TRUE
WRITE_LOCK_CAP     = TRUE
WRITE_LOCK_STATUS  = TRUE
READ_DISABLED_CAP  = TRUE
READ_ENABLED_CAP   = TRUE
READ_STATUS        = TRUE
READ_LOCK_CAP      = TRUE
READ_LOCK_STATUS   = TRUE

  INF SiliciumPkg/Sec/Sec.inf

  FILE FV_IMAGE = 9E21FD93-9C72-4c15-8C4B-E77F1DB2D792 {
    SECTION GUIDED EE4E5898-3914-4259-9D6E-DC7BD79403CF PROCESSING_REQUIRED = TRUE {
      SECTION FV_IMAGE = FVMAIN
    }
  }

  !include SiliciumPkg/Common.fdf.inc
"""

GAUGUIN_DEC = """##
#  Xiaomi Redmi Note 9 Pro 5G (gauguin)
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  DEC_SPECIFICATION = 0x00010005
  PACKAGE_NAME      = gauguinPkg
  PACKAGE_GUID      = 7E1B4C62-2F4A-4D18-9E31-2C5A0D8B6F42
  PACKAGE_VERSION   = 0.1
"""

GAUGUIN_TOML = """#
# Boot Shim Configs
#
[boot_shim]
requires_kernel_header = true

#
# UEFI FD Configs - the "UEFI FD" region from uefiplat.cfg
#
[uefi_fd]
base = 0x9FC00000
size = 0x300000

#
# Android Boot Image Kernel Configs
#
[boot_image_kernel]
kernel_compression = "gzip"
append_dtb         = true

#
# Android Boot Image Configs
#
[boot_image]
header_version = 1
"""


# ---------------------------------------------------------------------------
# The three !include files the FDF pulls in.
#
# DXE.inc / APRIORI.inc list the drivers that go into the firmware volume, in
# load order. Almost every one of them is a Qualcomm binary that we extracted
# from this phone's own XBL, so the lists are the same ones the sibling board
# packages use - taken from the reference platform and rewritten to point at
# `Binaries/gauguin/`, then filtered down to the drivers we actually have.
#
# The filter is the important part: shipping an INF for a driver whose .efi is
# missing fails the FDF at build time, and shipping a driver we do not have a
# blob for would silently give us a firmware volume that does not match the
# hardware.

REF_PLATFORM = "surya"          # Xiaomi POCO X3 NFC / SM7150 - closest sibling

# Drivers this XBL carries that the surya reference package does not list, but
# which 16-51 other platform packages in the tree do. surya is an older SoC
# generation; the older ordering omits them. Taken from Xiaomi's aliothPkg
# (SM8250) instead, and inserted at the same anchor line alioth puts them after,
# so the relative load order is the reference's, not this generator's invention.
#
# PILDxe/PILProxyDxe are deliberately NOT inserted: the reference has PILDxe
# commented out, and they exist to load ADSP/CDSP firmware, which nothing in a
# Windows boot path consumes.
EXTRA_DRIVERS = {
    "DXE.inc": [
        ("Drivers/CmdDbDxe/CmdDbDxe.inf",       "PwrUtilsDxe"),
        ("Drivers/ClockDxe/ClockDxe.inf",       "VcsDxe"),
        ("Drivers/TLMMDxe/TLMMDxe.inf",         "FeatureEnablerDxe"),
        ("Drivers/CipherDxe/CipherDxe.inf",     "MacDxe"),
    ],
    "APRIORI.inc": [
        ("Drivers/CmdDbDxe/CmdDbDxe.inf",       "PwrUtilsDxe"),
        ("Drivers/PdcDxe/PdcDxe.inf",           "VcsDxe"),
        ("Universal/Variable/RuntimeDxe/VariableRuntimeDxe.inf", "FeatureEnablerDxe"),
        ("Drivers/CipherDxe/CipherDxe.inf",     "MacDxe"),
    ],
}

# Driver name -> path under Binaries/<device>/, for the EXTRA_DRIVERS entries.
EXTRA_PATHS = {
    "PwrUtilsDxe":      "QcomPkg/Drivers/PwrUtilsDxe/PwrUtilsDxe.inf",
    "VcsDxe":           "QcomPkg/Drivers/VcsDxe/VcsDxe.inf",
    "FeatureEnablerDxe": "QcomPkg/Drivers/FeatureEnablerDxe/FeatureEnablerDxe.inf",
    "MacDxe":           "QcomPkg/Drivers/MacDxe/MacDxe.inf",
}


def load_guid_table(mu_root):
    """Map RAW file name -> FILE FREEFORM GUID, from the whole Mu-Silicium tree.

    Qualcomm's panel and config files have fixed firmware-file GUIDs that every
    platform package in the tree reuses verbatim (verified: `uefipil.cfg` is
    21E9BDD9-... in surya, cepheus, vayu and marble alike). Reading them out of
    the tree beats inventing our own, because Qualcomm's own signed drivers are
    what look these files up.
    """
    table = {}
    for inc in glob.glob(os.path.join(mu_root, "Platforms/*/*/Include/RAW.inc")):
        text = open(inc, encoding="utf-8", errors="replace").read()
        for m in re.finditer(r'FILE FREEFORM = ([0-9A-Fa-f-]{36})\s*\{(.*?)\n\s*\}',
                             text, re.S):
            ui = re.search(r'SECTION UI = "([^"]+)"', m.group(2))
            if ui:
                table.setdefault(ui.group(1), m.group(1).upper())
    return table


def rewrite_incs(ref_dir, have, device):
    """Produce (dxe_inc, apriori_inc) for `device` from the reference package.

    `have` is the set of `QcomPkg/Drivers/.../*.inf` paths present under
    Binaries/<device>. Reference lines we cannot satisfy are commented out
    rather than dropped, so the gap stays visible in the generated file.
    """
    out = {}
    referenced = set()
    for name, key in (("DXE.inc", "dxe_inc"), ("APRIORI.inc", "apriori_inc")):
        src = os.path.join(ref_dir, "Include", name)
        text = open(src, encoding="utf-8", errors="replace").read()
        text = text.replace(f"Binaries/{REF_PLATFORM}/", f"Binaries/{device}/")

        lines, dropped = [], []
        for line in text.splitlines():
            m = re.match(r'^(\s*)INF Binaries/(\S+)', line)
            # `have` is keyed the way present_drivers() builds it - relative to
            # Binaries/<device>/ - so strip the device component the rename
            # above introduced before comparing.
            rel = m.group(2).split("/", 1)[1] if m and "/" in m.group(2) else None
            if m and rel not in have:
                dropped.append(m.group(2))
                lines.append(f"# dropped, no blob extracted from this XBL: {m.group(2)}")
                continue
            if m:
                referenced.add(rel)
            lines.append(line)

        # Insert the drivers surya's generation predates, at their alioth anchors.
        for anchor, name in EXTRA_DRIVERS.get(name, []):
            path = EXTRA_PATHS[name]
            if path not in have or path in referenced:
                continue
            idx = next((i for i, l in enumerate(lines) if anchor in l), None)
            if idx is None:
                dropped.append(f"{path}  (no anchor line for {anchor})")
                continue
            lines.insert(idx + 1, f"  INF Binaries/{device}/{path}")
            referenced.add(path)

        header = (f"##\n"
                  f"#  GENERATED by tools/make_uefi_platform.py from the\n"
                  f"#  {REF_PLATFORM}Pkg reference package - do not edit by hand.\n"
                  f"#\n"
                  f"#  Rewritten to Binaries/{device}/ and filtered to the drivers this\n"
                  f"#  project actually extracted from the device's own XBL.\n")
        if dropped:
            header += "#\n#  Not available (commented out below):\n"
            header += "".join(f"#    {d}\n" for d in sorted(set(dropped)))
        header += "##\n"
        out[key] = header + "\n".join(lines) + "\n"
        out[key + "_dropped"] = dropped
    out["referenced"] = referenced
    return out


def emit_raw_inc(raw_dir, guid_table, device):
    """Generate RAW.inc from the config and panel files we actually extracted.

    These are the FREEFORM files the firmware volume has to carry for Qualcomm's
    signed drivers to find their configuration: the UEFI PIL config, the charger
    and secure-partition configs, the boot menu, the boot logo, the battery
    indicator bitmaps, and the display panel descriptions.
    """
    names = sorted(f[:-4] for f in os.listdir(raw_dir) if f.endswith(".raw"))
    known, fresh = [], []
    for n in names:
        (known if n in guid_table else fresh).append(n)

    w = ["##",
         "#  GENERATED by tools/make_uefi_platform.py - do not edit by hand.",
         "#",
         f"#  {len(names)} FREEFORM files recovered from this device's XBL:",
         f"#    {len(known)} carry a GUID already used elsewhere in Mu-Silicium and are",
         "#       emitted with it, because Qualcomm's signed drivers look these files",
         "#       up by firmware-file GUID.",
         f"#    {len(fresh)} are not referenced by any existing platform package; their",
         "#       GUIDs are generated deterministically here. Nothing looks them up by",
         "#       GUID, so the value only has to be unique.",
         "##", ""]

    for n in names:
        if n in guid_table:
            guid, note = guid_table[n], ""
        else:
            guid, note = guid_for(n), "  # generated"
        w.append(f'  FILE FREEFORM = {guid} {{')
        w.append(f'    SECTION UI = "{n}"')
        w.append(f'    SECTION RAW = Binaries/{device}/RawFiles/{n}')
        w.append(f'  }}{note}')
        w.append("")
    return "\n".join(w).rstrip() + "\n"


def write_common(out_root, packagename, socinc, model):
    """Write the DSC/FDF/DEC/INC files a Mu-Silicium platform package needs."""
    pkg = os.path.join(out_root, "Platforms/Xiaomi", f"{packagename}Pkg")
    os.makedirs(os.path.join(pkg, "Include"), exist_ok=True)

    files = {
        f"{packagename}.dsc": model["dsc"],
        f"{packagename}.fdf": GAUGUIN_FDF,
        f"{packagename}.dec": GAUGUIN_DEC,
        "Include/DXE.inc": model["dxe_inc"],
        "Include/APRIORI.inc": model["apriori_inc"],
        "Include/RAW.inc": model["raw_inc"],
    }
    for name, text in files.items():
        with open(os.path.join(pkg, name), "w") as fh:
            fh.write(text)
    return pkg


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=REPO)
    ap.add_argument("--out", default=None,
                    help="where to write the packages (default: <repo>/uefi)")
    ap.add_argument("--dxe-dir", default=None,
                    help="extracted DXE drivers (default: <repo>/device/dxe)")
    ap.add_argument("--mu", default=None,
                    help="Mu-Silicium checkout (default: <repo>/work/uefi/Mu-Silicium)")
    args = ap.parse_args()

    cfg = os.path.join(args.repo, "device/config/uefiplat.cfg")
    if not os.path.isfile(cfg):
        sys.exit(f"missing {cfg}")
    out_root = args.out or os.path.join(args.repo, "uefi")
    dxe_dir = args.dxe_dir or os.path.join(args.repo, "device/dxe")
    mu_root = args.mu or os.path.join(args.repo, "work/uefi/Mu-Silicium")

    memory, registers, params = parse_uefiplat(cfg)
    print(f"uefiplat.cfg: {len(memory)} DDR regions, {len(registers)} register "
          f"regions, {len(params)} config parameters")

    soc = os.path.join(out_root, "Silicon/Qualcomm/BitraPkg")
    board = os.path.join(out_root, "Platforms/Xiaomi/gauguinPkg")
    for d in (os.path.join(soc, "Library/MemoryMapLib"),
              os.path.join(soc, "Library/PlatformSecLib"),
              os.path.join(soc, "Library/AcpiTableUpdateLib"),
              os.path.join(board, "Library/MemoryMapLib"),
              os.path.join(board, "Library/ConfigurationMapLib"),
              os.path.join(board, "Include"),
              os.path.join(out_root, "Binaries/gauguin/RawFiles"),
              os.path.join(out_root, "Resources/Configs")):
        os.makedirs(d, exist_ok=True)

    with open(os.path.join(soc, "BitraPkg.dsc.inc"), "w") as fh:
        fh.write(BITRA_DSC_INC.format(**SOC_DEFAULTS))
    print("wrote BitraPkg.dsc.inc")

    with open(os.path.join(board, "Library/MemoryMapLib/MemoryMapLib.c"), "w") as fh:
        n = emit_memmap(memory, registers, fh)
    print(f"wrote MemoryMapLib.c ({n} regions)")

    with open(os.path.join(board, "Library/ConfigurationMapLib/ConfigurationMapLib.c"), "w") as fh:
        n = emit_configmap(params, fh)
    print(f"wrote ConfigurationMapLib.c ({n} entries)")

    # The driver lists come from the reference package, filtered to the blobs we
    # actually extracted. Checked rather than assumed: an INF without a matching
    # .efi is a build failure, and a driver we lack is a hole in the firmware.
    if not os.path.isdir(dxe_dir):
        sys.exit(f"missing {dxe_dir} - run tools/xbl_extract.py first")
    have = present_drivers(dxe_dir)

    ref_dir = os.path.join(mu_root, "Platforms/Xiaomi", f"{REF_PLATFORM}Pkg")
    if not os.path.isdir(ref_dir):
        sys.exit(f"missing reference package {ref_dir}\n"
                 f"clone Mu-Silicium into {mu_root} first")
    model = rewrite_incs(ref_dir, have, "gauguin")

    guid_table = load_guid_table(mu_root)
    model["raw_inc"] = emit_raw_inc(dxe_dir, guid_table, "gauguin")
    model["dsc"] = GAUGUIN_DSC
    print(f"wrote DXE.inc / APRIORI.inc ({len(have)} drivers), "
          f"RAW.inc ({len(glob.glob(os.path.join(dxe_dir, '*.raw')))} files, "
          f"{len(guid_table)} GUIDs on file)")

    # Blobs we have but the reference lists never mention. Not a failure - the
    # reference is a different board - but each one is a driver that would be
    # silently left out of the firmware, so they are named rather than buried.
    orphans = sorted(have - model.pop("referenced"))
    if orphans:
        print(f"  {len(orphans)} blobs are packaged but not listed by the "
              f"{REF_PLATFORM} reference:")
        for o in orphans:
            print(f"    {o}")

    pkg = write_common(out_root, "gauguin", "BitraPkg/BitraPkg.dsc.inc", model)
    print(f"wrote platform package {pkg}")

    toml = os.path.join(out_root, "Resources/Configs/gauguin.toml")
    with open(toml, "w") as fh:
        fh.write(GAUGUIN_TOML)
    print(f"wrote {os.path.relpath(toml, out_root)}")

    print(f"\npackages written under {out_root}")
    print("next: tools/sync-uefi-platform.sh to install them into the Mu-Silicium tree")


if __name__ == "__main__":
    main()
