#!/usr/bin/env python3
"""Can `PromoteMemoryResource` fire on this device? Answer it from the sources.

docs/08 step 4.18 narrowed the 27 failed `CoreLoadImage`s to heap state at the
instant each request arrives, and named one remaining alternative: a mechanism
that hands the allocator memory *mid-run*, which would explain a boundary that
is neither a running total nor the size of the request. There is exactly one
such mechanism in DxeCore - `PromoteMemoryResource` (Mem/Page.c) - and it was
read verbatim in step 4.20. It promotes untested `EfiGcdMemoryTypeReserved`
regions into `EfiConventionalMemory`, en masse, at whatever point in the run
the request that needs it arrives.

This device declares several `Reserv` DDR regions, so whether it can fire is a
real question. It is also a question the host can answer without a flash, and
the answer is not obvious by inspection, because the gate is not on the
platform's own vocabulary. The descriptor says `Reserv` and `SYS_MEM_CAP`; the
gate tests bits in a *different* namespace (`EFI_MEMORY_PRESENT|INITIALIZED`
set, `EFI_MEMORY_TESTED` clear), and the translation between them runs through
two lookup tables in two other files, one of which (`MEMORY_ATTRIBUTE_MASK`)
quietly decides whether a `SYSTEM_MEMORY` region is system memory or reserved.

So rather than argue it, this evaluates it: parse the device's own generated
memory map, apply Gcd.c's descriptor-to-GCD conversion and Page.c's gate
exactly as written, and print the verdict per region. Everything is read from
the tree; nothing about the mapping is restated here.

    tools/promote-check.py [--uefi-root DIR]
"""

import argparse
import os
import re
import sys

REPO = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
DEFAULT_ROOT = os.path.join(REPO, "work", "uefi", "Mu-Silicium")

# Two roots, because the file that matters here lives in neither the same place
# as its consumer nor the same place as its own vocabulary:
#
#   * the memory map itself is generated by tools/make_uefi_platform.py, so it
#     is committed in this repository and then copied into the checkout by
#     tools/sync-uefi-platform.sh. The copy in the checkout is the one that was
#     built, so that is the one read when it exists - and it is compared against
#     the committed one, because an analysis of a map that is not the map in the
#     image would be worse than no analysis.
#   * the vocabulary (MemoryMapLib.h) and the two rules being applied (Gcd.c,
#     Page.c) are upstream Mu-Silicium / Mu_Basecore, so they come from the
#     checkout.
MEMORY_MAP_C = "uefi/Platforms/Xiaomi/gauguinPkg/Library/MemoryMapLib/MemoryMapLib.c"
MEMORY_MAP_C_INSTALLED = "Platforms/Xiaomi/gauguinPkg/Library/MemoryMapLib/MemoryMapLib.c"
# The vocabulary the descriptors are written in, and the values behind it.
MEMORY_MAP_H = "Silicon/Silicium/SiliciumPkg/Include/Library/MemoryMapLib.h"
PIHOB_H = "Mu_Basecore/MdePkg/Include/Pi/PiHob.h"
UEFISPEC_H = "Mu_Basecore/MdePkg/Include/Uefi/UefiSpec.h"
# The three bits the gate tests are DxeCore's own, not UEFI's: they are defined
# in DxeMain.h and are not part of any spec's memory-capability set.
DXEMAIN_H = "Mu_Basecore/MdeModulePkg/Core/Dxe/DxeMain.h"
# The two rules being applied.
GCD_C = "Mu_Basecore/MdeModulePkg/Core/Dxe/Gcd/Gcd.c"
PAGE_C = "Mu_Basecore/MdeModulePkg/Core/Dxe/Mem/Page.c"

MAX_ALLOC_ADDRESS = (1 << 48) - 1


def read(root, rel):
    path = os.path.join(root, rel)
    try:
        with open(path, "r", errors="replace") as fh:
            return fh.read()
    except OSError as exc:
        sys.exit(f"promote-check: cannot read {rel}: {exc}")


def defines(text):
    """Every `#define NAME VALUE` in a header, with continuations joined.

    Values are left as source expressions; resolve() evaluates them.
    """
    out = {}
    # Join backslash continuations first: Gcd.c's masks are written across
    # four lines each and the macro is unreadable without this.
    text = re.sub(r"\\\n", " ", text)
    for m in re.finditer(r"^#define\s+(\w+)\s+(.+?)\s*$", text, re.M):
        name, value = m.group(1), m.group(2).strip()
        value = re.sub(r"/\*.*?\*/", "", value).strip()
        # Function-like macros and casts are not needed here.
        if value.startswith("(") and ")" in value[:2]:
            continue
        out[name] = value
    return out


def resolve(name, table, seen=None):
    """Evaluate a #define in terms of other #defines and integer literals."""
    seen = seen or set()
    if name in seen:
        raise KeyError(f"circular #define: {name}")
    if name not in table:
        raise KeyError(name)
    seen = seen | {name}
    value = table[name]

    def sub(m):
        token = m.group(0)
        if token in table:
            return str(resolve(token, table, seen))
        return token

    expr = re.sub(r"\b[A-Za-z_]\w*\b", sub, value)
    expr = re.sub(r"([0-9A-Fa-fx]+)[uUlL]+", r"\1", expr)
    return int(eval(expr, {"__builtins__": {}}, {}))  # noqa: S307 - tree-local constants


def parse_descriptors(text):
    """The generated `gMemoryDescriptor[]` table, as written."""
    body = text.split("gMemoryDescriptor[] = {", 1)[1].split("};", 1)[0]
    rows = []
    for line in body.splitlines():
        line = line.strip()
        if not line.startswith("{") or line.startswith("//"):
            continue
        m = re.match(
            r'\{\s*"([^"]*)"\s*,\s*(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)\s*,'
            r"\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\}",
            line,
        )
        if not m:
            sys.exit(f"promote-check: unparsed descriptor line: {line}")
        rows.append(
            dict(
                name=m.group(1),
                address=int(m.group(2), 16),
                length=int(m.group(3), 16),
                hob=m.group(4),
                rtype=m.group(5),
                attr=m.group(6),
                memtype=m.group(7),
            )
        )
    return rows


def parse_conversion_table(text):
    """Gcd.c's mAttributeConversionTable: (resource attribute, capability, memory-only)."""
    body = text.split("mAttributeConversionTable[] = {", 1)[1].split("};", 1)[0]
    entries = []
    for m in re.finditer(
        r"\{\s*(EFI_RESOURCE_ATTRIBUTE_\w+)\s*,\s*(EFI_MEMORY_\w+)\s*,\s*(TRUE|FALSE)\s*\}",
        body,
    ):
        entries.append((m.group(1), m.group(2), m.group(3) == "TRUE"))
    if not entries:
        sys.exit("promote-check: mAttributeConversionTable not found in Gcd.c")
    return entries


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--uefi-root", default=os.path.normpath(DEFAULT_ROOT))
    ap.add_argument("--repo-root", default=REPO)
    args = ap.parse_args()
    root = args.uefi_root

    committed = os.path.join(args.repo_root, MEMORY_MAP_C)
    installed = os.path.join(root, MEMORY_MAP_C_INSTALLED)
    mm_path, note = committed, ""
    if os.path.exists(installed):
        mm_path = installed
        import hashlib

        def digest(path):
            with open(path, "rb") as fh:
                return hashlib.md5(fh.read()).hexdigest()

        if digest(installed) != digest(committed):
            note = (f"  ** the checkout copy differs from the committed one "
                    f"({digest(installed)[:8]} vs {digest(committed)[:8]}): this is the\n"
                    f"     map that was built, not the map in the repository.\n")
    mm_c = read(os.path.dirname(mm_path), os.path.basename(mm_path))
    mm_table = defines(read(root, MEMORY_MAP_H))
    pi_table = defines(read(root, PIHOB_H))
    spec_table = defines(read(root, UEFISPEC_H))
    spec_table.update(defines(read(root, DXEMAIN_H)))
    gcd_c = read(root, GCD_C)
    page_c = read(root, PAGE_C)
    gcd_table = defines(gcd_c)

    # Merge, with the header's aliases taking precedence over nothing: the two
    # files do not collide (PeiHob.h-style resource attributes vs our aliases).
    table = {}
    table.update(pi_table)
    table.update(spec_table)
    table.update(mm_table)

    def val(name):
        return resolve(name, table)

    present = val("EFI_RESOURCE_ATTRIBUTE_PRESENT")
    initialized = val("EFI_RESOURCE_ATTRIBUTE_INITIALIZED")
    tested = val("EFI_RESOURCE_ATTRIBUTE_TESTED")
    memory_attr_mask = resolve("MEMORY_ATTRIBUTE_MASK", {**table, **gcd_table})
    tested_attrs = resolve("TESTED_MEMORY_ATTRIBUTES", {**table, **gcd_table})
    init_attrs = resolve("INITIALIZED_MEMORY_ATTRIBUTES", {**table, **gcd_table})
    present_attrs = resolve("PRESENT_MEMORY_ATTRIBUTES", {**table, **gcd_table})

    mem_present = val("EFI_MEMORY_PRESENT")
    mem_init = val("EFI_MEMORY_INITIALIZED")
    mem_tested = val("EFI_MEMORY_TESTED")

    # Resource type -> GcdMemoryType, from the switch at Gcd.c:2653-2699. The
    # three SYSTEM_MEMORY tests are separate `if`s in the original, so the last
    # one that matches wins - reproduced here in the same order rather than
    # collapsed into a mapping, because that ordering is the thing that decides
    # whether `Kernel` is system memory or reserved.
    rt = {name: val(name) for name in
          ("EFI_RESOURCE_SYSTEM_MEMORY", "EFI_RESOURCE_MEMORY_RESERVED",
           "EFI_RESOURCE_MEMORY_MAPPED_IO", "EFI_RESOURCE_FIRMWARE_DEVICE",
           "EFI_RESOURCE_MEMORY_MAPPED_IO_PORT", "EFI_RESOURCE_MEMORY_UNACCEPTED",
           "EFI_RESOURCE_IO", "EFI_RESOURCE_IO_RESERVED")}

    def gcd_type(resource_type, attr):
        if resource_type == rt["EFI_RESOURCE_SYSTEM_MEMORY"]:
            kind = "NonExistent"
            masked = attr & memory_attr_mask
            if masked == tested_attrs:
                if attr & val("EFI_RESOURCE_ATTRIBUTE_MORE_RELIABLE"):
                    kind = "MoreReliable"
                else:
                    kind = "SystemMemory"
            if masked == init_attrs:
                kind = "Reserved"
            if masked == present_attrs:
                kind = "Reserved"
            if attr & val("EFI_RESOURCE_ATTRIBUTE_SPECIAL_PURPOSE"):
                kind = "SystemMemory"
            if attr & val("EFI_RESOURCE_ATTRIBUTE_PERSISTENT"):
                kind = "Persistent"
            return kind
        if resource_type in (rt["EFI_RESOURCE_MEMORY_MAPPED_IO"], rt["EFI_RESOURCE_FIRMWARE_DEVICE"]):
            return "MemoryMappedIo"
        if resource_type in (rt["EFI_RESOURCE_MEMORY_MAPPED_IO_PORT"], rt["EFI_RESOURCE_MEMORY_RESERVED"]):
            return "Reserved"
        if resource_type == rt["EFI_RESOURCE_MEMORY_UNACCEPTED"]:
            return "Unaccepted"
        return "None"

    conv = parse_conversion_table(gcd_c)
    conv = [(val(a), val(c), memory_only) for a, c, memory_only in conv]

    def capabilities(kind, attr):
        caps = 0
        for attribute, capability, memory_only in conv:
            if memory_only or kind not in ("SystemMemory", "MoreReliable"):
                if attr & attribute:
                    caps |= capability
        return caps

    # Page.c's gate, verbatim. The comment in the source spells out why TESTED
    # must be clear: a region nobody has tested is the one thing it is willing
    # to hand out, so a region that declares itself tested is not a candidate.
    gate_needs = mem_present | mem_init
    gate_excludes = mem_tested

    rows = parse_descriptors(mm_c)
    print("promote-check: can PromoteMemoryResource (Mem/Page.c) fire on this device?\n")
    print(f"reads: {os.path.relpath(mm_path, args.repo_root) if mm_path.startswith(args.repo_root) else mm_path}")
    print(f"       {MEMORY_MAP_H}  {PIHOB_H}  {UEFISPEC_H}  {DXEMAIN_H}")
    print(f"       {GCD_C}  {PAGE_C}\n")
    if note:
        print(note)
    print("the gate is not in the descriptor's own vocabulary:")
    print(f"  EFI_MEMORY_PRESENT     {mem_present:#018x}  must be set")
    print(f"  EFI_MEMORY_INITIALIZED {mem_init:#018x}  must be set")
    print(f"  EFI_MEMORY_TESTED      {mem_tested:#018x}  must be CLEAR")
    print()
    print("the capability column shows only those three bits, because they are the")
    print("only ones the gate reads; a region can be otherwise fully capable and")
    print("still read -/-/- here. They arrive by a route worth knowing: Gcd.c's")
    print("conversion table marks them `Memory = FALSE`, which means they are")
    print("converted only for a GcdMemoryType that is *not* system memory - so a")
    print("Reserved region carries them and a SystemMemory one does not.")
    print()
    print(f"{'region':<16} {'hob':<10} {'resource':<9} {'gcd type':<13} {'caps P/I/T':<12} verdict")
    print(f"{'-'*16} {'-'*10} {'-'*9} {'-'*13} {'-'*12} {'-'*40}")

    promotable = []
    for row in rows:
        attr = val(row["attr"])
        kind = gcd_type(val(row["rtype"]), attr)
        caps = capabilities(kind, attr)
        p = "P" if caps & mem_present else "-"
        i = "I" if caps & mem_init else "-"
        t = "T" if caps & mem_tested else "-"

        if row["hob"] == "NoHob":
            # AddHob (MemoryInitPei.c) only calls BuildResourceDescriptorHob
            # for AddMem / AddDev / HobOnlyNoCacheSetting, so this region has no
            # HOB and therefore no GCD entry at all.
            verdict = "not in the GCD map (no HOB built)"
        elif kind != "Reserved":
            verdict = f"no: gcd type is {kind}, gate needs Reserved"
        elif (caps & (gate_needs | gate_excludes)) != gate_needs:
            missing = [n for n, b in (("PRESENT", mem_present), ("INITIALIZED", mem_init))
                       if not caps & b]
            extra = ["TESTED"] if caps & gate_excludes else []
            bits = ", ".join(missing + [f"{e} set" for e in extra])
            verdict = f"no: {bits}"
        else:
            verdict = "YES - promotable"
            promotable.append(row)

        caps_str = f"{p}/{i}/{t}"
        print(f"{row['name']:<16} {row['hob']:<10} {row['rtype']:<9} {kind:<13} "
              f"{caps_str:<12} {verdict}")

    print()
    ddrs = [r for r in rows if r["hob"] != "NoHob"]
    reserved = [r for r in ddrs if gcd_type(val(r["rtype"]), val(r["attr"])) == "Reserved"]
    print(f"{len(rows)} descriptors, {len(ddrs)} with a resource HOB, "
          f"{len(reserved)} landing in the GCD map as Reserved")
    for r in reserved:
        print(f"  {r['name']:<16} {r['length']:#012x}  {r['memtype']}")
    print()
    if promotable:
        total = sum(r["length"] for r in promotable)
        print(f"-> {len(promotable)} region(s) promotable, {total / (1 << 20):.1f} MiB in one step")
        print("   PromoteMemoryResource can fire here: a mid-run promotion is a live")
        print("   explanation for a boundary that is neither a running total nor the request.")
    else:
        print("-> no descriptor on this device satisfies the gate")
        print("   PromoteMemoryResource cannot fire. It returns FALSE from every call")
        print("   site on this board (FindFreePages' third rung, and the CoreConvertPages")
        print("   failure path in CoreInternalAllocatePages), so nothing can enter")
        print("   EfiConventionalMemory mid-run. The heap only shrinks; the 27 failures")
        print("   are heap state at request time and not an injected region.")
        print()
        print("   The same predicate, verbatim, is also the first test in Misc/")
        print("   MemoryProtection.c's guard-page pass, so that pass skips nothing here.")
        print("   Every other route into EfiConventionalMemory (CoreAddMemoryDescriptor,")
        print("   CoreFreePages, CoreFreePoolPages) is either DXE-init time or a page")
        print("   coming back. There is no path that grows the heap during dispatch.")
        print("   That leaves P2 ERR as the only route to the reason.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
