#!/usr/bin/env bash
#
# Install the generated gauguin UEFI platform into a Mu-Silicium checkout.
#
# The packages under `uefi/` are generated by tools/make_uefi_platform.py and
# tools/make_xbl_binaries.py; nothing here is hand-written. This script only
# puts them where Mu-Silicium's build expects to find them, compiling the DTB
# on the way, and then optionally builds.
#
# Mu-Silicium builds the *whole* firmware from a checkout that also carries 40
# other devices' packages. Everything this script installs is inside a path
# named gauguin, so a sync is additive and a re-sync overwrites only our own
# files - with one exception, noted below (the DTB directory is shared).
#
# Usage:  sync-uefi-platform.sh [--mu DIR] [--build] [--clean]

set -euo pipefail

REPO=$(cd "$(dirname "$0")/.." && pwd)
MU=${MU:-$REPO/work/uefi/Mu-Silicium}
GEN=$REPO/uefi
BUILD=0

while [ $# -gt 0 ]; do
    case "$1" in
        --mu)     MU=$2; shift 2 ;;
        --clean)  CLEAN=--clean; shift ;;
        --build)  BUILD=1; shift ;;
        -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
done

die() { echo "error: $*" >&2; exit 1; }
say() { printf '\033[1m== %s\033[0m\n' "$*"; }

[ -d "$MU" ] || die "no Mu-Silicium checkout at $MU (use --mu)"
[ -d "$GEN" ] || die "no generated packages at $GEN - run tools/make_uefi_platform.py"
[ -f "$MU/build_uefi.py" ] || die "$MU does not look like a Mu-Silicium checkout"

# The generator is the source of truth; refuse to sync a stale tree rather than
# silently building something that does not match the device data.
need=(
    "$GEN/Platforms/Xiaomi/gauguinPkg/gauguin.dsc"
    "$GEN/Platforms/Xiaomi/gauguinPkg/gauguin.fdf"
    "$GEN/Platforms/Xiaomi/gauguinPkg/DeviceBuild.py"
    "$GEN/Platforms/Xiaomi/gauguinPkg/Include/DXE.inc"
    "$GEN/Platforms/Xiaomi/gauguinPkg/Include/APRIORI.inc"
    "$GEN/Platforms/Xiaomi/gauguinPkg/Include/RAW.inc"
    "$GEN/Silicon/Qualcomm/BitraPkg/BitraPkg.dsc.inc"
    "$GEN/Resources/Configs/gauguin.toml"
)
for f in "${need[@]}"; do
    [ -f "$f" ] || die "missing $f - re-run tools/make_uefi_platform.py"
done

# ---------------------------------------------------------------------------
say "installing platform package"
# ---------------------------------------------------------------------------
install -d "$MU/Platforms/Xiaomi/gauguinPkg"
cp -a "$GEN/Platforms/Xiaomi/gauguinPkg/." "$MU/Platforms/Xiaomi/gauguinPkg/"
echo "   Platforms/Xiaomi/gauguinPkg  ($(find "$GEN/Platforms/Xiaomi/gauguinPkg" -type f | wc -l) files)"

# ---------------------------------------------------------------------------
say "installing SoC package"
# ---------------------------------------------------------------------------
# BitraPkg is the SM7225 layer. Mu-Silicium has no BitraPkg, and the name does
# not collide with anything in Silicon/Qualcomm, so this is a clean addition.
install -d "$MU/Silicon/Qualcomm/BitraPkg"
cp -a "$GEN/Silicon/Qualcomm/BitraPkg/." "$MU/Silicon/Qualcomm/BitraPkg/"
echo "   Silicon/Qualcomm/BitraPkg"

# ---------------------------------------------------------------------------
say "installing device binaries"
# ---------------------------------------------------------------------------
# 55 signed Qualcomm DXE drivers + 32 config/panel files, all extracted from
# this phone's own XBL. These are Qualcomm's signed images; they are used
# verbatim, which is the only way they will load - see the note about Integrity
# Checks in the DSC.
install -d "$MU/Binaries/gauguin"
cp -a "$GEN/Binaries/gauguin/." "$MU/Binaries/gauguin/"
echo "   Binaries/gauguin  ($(find "$GEN/Binaries/gauguin" -type f | wc -l) files)"

# ---------------------------------------------------------------------------
say "installing device config"
# ---------------------------------------------------------------------------
install -d "$MU/Resources/Configs"
cp "$GEN/Resources/Configs/gauguin.toml" "$MU/Resources/Configs/gauguin.toml"
echo "   Resources/Configs/gauguin.toml"

# ---------------------------------------------------------------------------
say "building the device tree"
# ---------------------------------------------------------------------------
DTS=$REPO/dts/sm7225-xiaomi-gauguin.dts
PREBUILT=$REPO/work/out/sm7225-xiaomi-gauguin.dtb
KERNEL=$REPO/work/linux
[ -f "$DTS" ] || die "missing $DTS"

install -d "$MU/Resources/DTBs"

# build_uefi.py appends Resources/DTBs/<device>.dtb to the UEFI image, and the
# Android bootloader validates that DTB's qcom,msm-id before it will accept the
# image at all - which is why this has to be OUR device tree and not a
# placeholder. The board file uses #include and #define, so it needs the C
# preprocessor first; the kernel build already does exactly this, so its output
# is preferred over re-deriving it here.
if [ -f "$PREBUILT" ] && [ "$KERNEL/arch/arm64/boot/dts/qcom/sm6350.dtsi" -nt "$PREBUILT" ]; then
    echo "   note: the DTS is newer than the built DTB - re-run tools/build-kernel.sh"
fi

if [ -f "$PREBUILT" ]; then
    cp "$PREBUILT" "$MU/Resources/DTBs/gauguin.dtb"
    echo "   Resources/DTBs/gauguin.dtb  ($(stat -c%s "$MU/Resources/DTBs/gauguin.dtb") bytes, from the kernel build)"
elif [ -f "$KERNEL/arch/arm64/boot/dts/qcom/sm6350.dtsi" ]; then
    if cpp -nostdinc -undef -x assembler-with-cpp \
           -I "$KERNEL/arch/arm64/boot/dts/qcom" -I "$KERNEL/include" \
           "$DTS" /tmp/gauguin.dts.pp 2>/tmp/cpp-gauguin.log &&
       dtc -I dts -O dtb -o "$MU/Resources/DTBs/gauguin.dtb" /tmp/gauguin.dts.pp 2>/tmp/dtc-gauguin.log; then
        echo "   Resources/DTBs/gauguin.dtb  ($(stat -c%s "$MU/Resources/DTBs/gauguin.dtb") bytes, preprocessed locally)"
    else
        sed 's/^/     /' /tmp/cpp-gauguin.log /tmp/dtc-gauguin.log 2>/dev/null | head -20
        die "could not build the device tree"
    fi
else
    die "no device tree available: neither $PREBUILT nor a kernel tree at $KERNEL"
fi

# A parity copy, decompiled, so the DTB that ships can be read back and
# compared against the source without a separate tool. The reference packages
# keep both files; only the .dtb is used by the build.
dtc -I dtb -O dts -o "$MU/Resources/DTBs/gauguin.dts" "$MU/Resources/DTBs/gauguin.dtb" 2>/dev/null &&
    echo "   Resources/DTBs/gauguin.dts  (decompiled for review)"

# ---------------------------------------------------------------------------
if [ "$BUILD" = 0 ]; then
    say "installed. Build with:"
    echo "   cd $MU && source setup_env.sh -p apt && python3 build_uefi.py -d gauguin -r DEBUG ${CLEAN:-}"
    exit 0
fi

# ---------------------------------------------------------------------------
say "building"
# ---------------------------------------------------------------------------
cd "$MU"
# shellcheck disable=SC1091
source ./setup_env.sh -p apt >/dev/null 2>&1 || die "setup_env.sh failed"
python3 build_uefi.py -d gauguin -r DEBUG ${CLEAN:-}

say "output"
ls -l "$MU"/Mu-gauguin*.img "$MU"/Mu-gauguin*.bin 2>/dev/null || \
    echo "   no image produced - build log above"
